
language: cpp
os:
- linux
compiler:
  - gcc

script : make -C algorithm


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN 
  file: "algorithm/solver/2/bin/libpocketcube.so"
  skip_cleanup: true
  on:
      tags: true

