
language: cpp
os:
- osx
compiler:
  - gcc

script : make -C algorithm


deploy:
  provider: releases
  api_key: 93a1d895585c21885a7a08a838448e3198fcbea9
  file: "algorithm/solver/2/bin/libpocketcube.so"
  skip_cleanup: true
  on:
    tags: true

